### ISSUE TITLE
Create MongoDB services

### ISSUE THREAD

**Issue by tntrex** [dockeronfire/localhost-docker#1]
Create MongoDB service with Web UI just like MySQL. Example mongo service for docker-compose:

```yml
services:
  mongo:
    image: mongo:3.6-jessie
    user: mongodb
    volumes:
      - mongodb:/data/db
    ports:
      - '27017'

volumes:
  mongodb:
```
